# Generated by Django 3.0.6 on 2020-05-12 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0002_produce_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produce',
            name='price',
        ),
    ]
