# Generated by Django 3.0.6 on 2020-05-21 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=75, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField()),
                ('itemsTotal', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('adjustments', models.CharField(choices=[('DISC', 'Discount'), ('TAX', 'Tax'), ('SHIP', 'Shipping')], default='DISC', max_length=20)),
                ('adjustmentsTotal', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('checkOut_status', models.CharField(choices=[('PEN', 'Pending'), ('CAN', 'Cancelled'), ('COM', 'Completed')], default='PEN', max_length=15)),
                ('currencyCode', models.CharField(default='UGX', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Customer')),
            ],
        ),
    ]
