# Generated by Django 3.0.6 on 2020-05-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200525_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.TextField(blank=True),
        ),
    ]
